# Change these first
owner: ideiascasa # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Workflow
    url: https://work.ideias.casa/healthz/readiness
    icon: https://work.ideias.casa/favicon.ico
    method: GET
  - name: Config (Noco)
    url: https://dados.ideias.casa/dashboard/
    method: GET
  - name: Metabase
    url: https://meta.ideias.casa/
    method: GET
  - name: Chatwoot
    url: https://chat.ideias.casa/android-icon-192x192.png
    method: GET
    icon: https://chat.ideias.casa/android-icon-192x192.png

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.ideias.casa
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status - Casa das Idéias
  introTitle: "Status dos serviços da Casa das Idéias"
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: Site
      href: https://ideias.casa/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
